name: Test Publish Profile Secret

on:
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Validate that the secret exists
        run: |
          if [ -z "${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}" ]; then
            echo "❌ Secret AZURE_WEBAPP_PUBLISH_PROFILE is EMPTY or not defined"
            exit 1
          else
            echo "✅ Secret AZURE_WEBAPP_PUBLISH_PROFILE exists and is defined (not printing for security)"
          fi
